name: Actionlint

on:
  push:
    branches: [main]
    paths: &paths
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/actionlint.*"
      - "mise.toml"
  pull_request:
    branches: [main]
    paths: *paths

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint GitHub Actions Workflows
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup mise
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
        with:
          experimental: true

      - name: Run actionlint
        run: mise run actionlint
